<h2>Fruit Trees Identification</h2>
<p>
There are trees that produce flowers that don't develop into fruits. There also trees that produces leaves and nothing else.  You can immediately identify a fruit tree if you see one. When you distinguish any kind of fruit hanging from a tree, then common sense would tell you that it is most probably a fruit tree. 
</p>
<p>
Fruit trees are very useful since it produces edible crop that anyone can eat or as an ingredient of a thousand of food recipes. The agricultural industry has boomed a lot of economies because fruit producing trees can very well become one's stable source of income. Not only are fruits very useful in food preparation, they can also be used as health supplements and as a diet to treat certain diseases. 
</p>
<p>
Identifying a fruit tree should be quite simple. The tricky part would be identifying which fruit tree type a tree belongs too. To help you identify fruit trees, here are each type's quick descriptions and some examples: 
</p>
<ul>
<li>Berries- this type of fruit tree produces fruits with a fleshy pericarp. Pericarp is a term that refers to the ovary wall of a fruit, which can be fleshy and soft when fruit ripens. Its outer layers can sometimes be tough or soft and may either have one or more than one seeds. 
Examples: Papaya, grapes, tomatoes, guava, sapote</li>
<li>Bacate- this also termed as berry-like trees. This type of trees is very much similar to berries except that they may or may not contain seeds and develop without fertilization and pollination
Examples: banana, avocado </li>
<li>Pepo- another type of berry tree that produce fruits with hard and thick rinds. They mainly belong to the gourd family. 
Examples: watermelon, pumpkin, squash </li>
<li>Hesperidium- you can identify this type of tree if you notice that its fruit have partitions or sections. The citrus fruit family is usually under this category. 
Examples: orange, grapefruit, lemon, </li>
<li>Drupe- if you chance upon fruits with a hard inner layer, particularly the layer that surrounds the seed, then they belong to the drupe group. Some drupes also have green, fleshy husk and hard endocarps. 
Examples: mango, almonds, walnuts, coconuts </li>
<li>Pome- this tree type is characterized with edible and fleshy hypanthium. Hypanthium is the term used to refer to the receptacle tissue that surrounds a fruit's core.  
Examples: pear, apple, loquat </li>
</ul>