<h2>Defining Tree Identification</h2>
<p>Tree identification, more formally dendrology, is the study of trees and shrubs and how to classify them into a taxonomy.  Woody plants belong to many different plant families which can contain both woody and none woody plants.  Tree identification is therefore difficult to distinguish from plant taxonomy - as trees may fall into the same categories as plants which are not trees.  </p>
<p>In industrial terms, dendrology is more concerned with identifying and clasifying those trees which are economically useful.  Tree identification is part of some academic courses, and in these cases includes all woody plants.  </p>
<p>Tree identification is a narrower field than botony (the study of all plants), and should not be confused.  The articles below discuss some tree identification topics:</p>

<ul>
	<li><a href="<?php echo $subdirectory ?>/what-is-a-tree.html" title="What is a tree">What is a tree?</a></li>
	<li><a href="<?php echo $subdirectory ?>/kids-tree-identification.html" title="A kids guide to tree identification">A kids guide to tree identification</a></li>
	<li><a href="<?php echo $subdirectory ?>/leaf-tree-identification.html" title="Tree identification by leaf shape">Tree identification by leaf shape</a></li>
	<li><a href="<?php echo $subdirectory ?>/leaf-shape.html" title="Why leaves are the shape they are?">Why leaves are the shape they are?</a></li>
	<li><a href="<?php echo $subdirectory ?>/bark-tree-identification.html" title="Tree identification by bark">Tree identification by bark</a></li>
	<li><a href="<?php echo $subdirectory ?>/tree-evolution.html" title="The evolution of trees">The evolution of trees</a></li>
	<li><a href="<?php echo $subdirectory ?>/dendrology.html" title="Dendrology - the study of trees">Dendrology - the study of trees</a></li>
	<li><a href="<?php echo $subdirectory ?>/tree-benefits.html" title="The benefits of trees">The benefits of trees</a></li>
	<li><a href="<?php echo $subdirectory ?>/tree-growing-regions.html" title="Why do different trees grow in different places?">Why do different trees grow in different places?</a></li>
	<li><a href="<?php echo $subdirectory ?>/identifying-tree-health-problems.html" title="Identifying tree health problems">Identifying tree health problems</a></li>
	<li><a href="<?php echo $subdirectory ?>/elm-tree-identification.html" title="Elm Tree Identification">Elm Tree Identification</a></li>
	<li><a href="<?php echo $subdirectory ?>/fruit-trees-identification.html" title="Fruit Trees Identification">Fruit Trees Identification</a></li>
	<li><a href="<?php echo $subdirectory ?>/maple-tree-identification.html" title="Maple Tree Identification">Maple Tree Identification</a></li>
	<li><a href="<?php echo $subdirectory ?>/oak-tree-identification.html" title="Oak Tree Identification">Oak Tree Identification</a></li>
	<li><a href="<?php echo $subdirectory ?>/palm-tree-identification.html" title="Palm Tree Identification">Palm Tree Identification</a></li>
	<li><a href="<?php echo $subdirectory ?>/pine-tree-identification.html" title="Pine Tree Identification">Pine Tree Identification</a></li>
</ul>