<h2>A Kids Guide to Tree Identification</h2>

Tree identification can be a fun way to learn more about what lives and grows all around you, even the trees in your back yard. When you are learning about tree identification you will begin to look at the trees in your yard, at your school, and at the local park in a whole new way. There are many great things to learn about trees, and when you realize how interesting trees are you値l wonder why you didn稚 notice them before.
<br /><br />
The first think you値l want to do for tree identification is to stand back and look at the whole tree. You値l want to take note of the overall shape of the tree, the colors it displays, and if there is anything unusual or remarkable about it. It might help to take notes, that way when you are going over everything you are sure you remember exactly the way it looked to make a real tree identification.
<br /><br />
Next, you値l want to get up close and really look at the bark. Is it smooth, furrowed, warty, scaly, plated, shaggy, papery, or fibrous? Really take a close look and see what you think, a tree identification field guide can help explain and give clear examples of what each type of bark looks like. Bark is sort of like a fingerprint for the tree, if you can identify what type of bark the tree has you are well on your way to tree identification.
<br /><br />
Next, you値l want to look at the leaves on the tree. If you can, find a leave to add to your own field guide or scrapbook. Look closely at the leaf, is it one continuous leaf, or is it a bunch of leaflets on one stem? Or, is it not very leafy at all, does it have needles? Knowing what the leaf looks like close up will help aid you in tree identification, because the leaves are much like the bark, unique to each tree. 
<br /><br />