<h2>Maple Tree Identification</h2>

There are over thirteen identified species of maple trees in North America alone. This does not include hundreds of maple species in all other countries and those that are yet to be discovered. 
<br /><br />
Here are the most common types of maples trees: 
<br />
Red Maple
These are medium-sized maple trees that have light gray barks, which grow darker and rougher as they age. They have a slender and shiny green twigs that would eventually turn red with vegetative buds growing in clusters. Its branches are quite low. Red maple leaves are notched with three to five lobes. Leaf colors ranges from light green to almost white in color. It changes its usual color to bright orange or red come autumn. 
<br /><br />
Norway Maple 
This type of maple tree originally breeds from Europe. They can grow as high as 50 feet. They have broader leaves than that of a red maple tree stretching to about 4-7 inches and have a total of five lobes. One can notice a milky sap if one of their leaf stalks is cut, twisted or pressed. Their twigs have a light brown to reddish-brown hue. Norway Maple leaves may also come in golden or multicolored colors. In fall, Norway maple leaves turn to yellow or green. This type of maple produces the most beautiful flowers. 
<br /><br />
Japanese Maple 
This type of maple tree has deciduous and broad leaves. They can reach as high as 25 feet in height and in spread. Their foliage can either be in variations of green or red. Come fall, their leaves turn to yellow, red or purple. They have green or reddish brown stems that are slender and smooth.  
<br /><br />
Silver Maple
Silver Maple trees are also called as soft maple, water maple or white maple. Their silver color comes from their grayish brown bark that later develop to irregular groves with grayish scaly plates. They are usually found beside bodies of water. In early spring, it produces beautiful red flowers that come in interesting clusters. Come fall, they produce    yellow foliage.
<br /><br />
Sugar Maple 
Sugar maple trees have green to dark-green leaves with 3 or 5 lobes. You can notice that its leaf margin does not have fine teeth. During fall, it turns to yellow, burnt orange or red. It has a widespread layout that makes it a good shade. Young sugar maples have gray barks that would eventually have furrows and irregular channels when they mature. 
