<h2>Oak Tree Identification</h2>
<p>
The oak tree has long been the symbol of endurance and strength. Oak is actually a common name of a number of tree species in the genus Quercus. This genus is popularly bred in the northern hemisphere primarily in America and parts of Asia. 
</p><p>
At A Glance 
The leaves of an oak tree are spirally arranged. Its leaves are serrated and have a smooth margin. It produces flowers during springtime called catkins. Acorn, a fruit nut with a cup-like appearance, is harvested from oak trees. An acorn may contain one to three seed that may take up to six months to one and a half year to fully mature. Some oak species may also have evergreen leaves. 
</p><p>
<strong>Classifications of Oak Trees</strong>
</p>
<ul>
<li>Cork Oaks (Leucobalanus; Lepidobalanus; Sect. Quercus)<br />
This type of oak tree is known to be the white oaks that are usually found in North America, Asia and Europe. Lobes of its leaves are round and they produce hairless acorn shells. </li>
<li>Turkey Oak (Sect. Cerris)<br />
This type of oak tree produces the bitterest acorns. Its leaves have sharp tips with some bristles at its lobe.</li>
<li>Hungarian Oaks (Sect. Mesobalanus)<br />
Often seen in Asia and Europe. Its leaves are long and produce bitter acorns that also come in hairless acorn shells. </li>
<li>Canyon Live Oaks (Sect. Protobalanus)<br />
This type of oak trees is commonly found in America and Mexico. They produce acorn shell woolly with leaves similar to that of Turkey Oak.</li>
<li>Red Oaks (Erythrobalanus; Sect. Lobatae)<br />
Red oaks are popularly seen in Central, North and Northern South America. They are very much similar with Canyon Live Oaks except for the red hues of its bark. </li>
</ul>
<p>
Relevance And Uses of Oak Trees 
Since oak trees are hardwood, they are popularly used as lumber materials for furniture. It is also used as flooring. Oak trees are also a good source of corks and even barrels for wines. Oak barrels are said to add a unique taste, color and aroma to the wine it stores. In the medical arena, the barks of white oak trees are also used as key components in some medicines. Acorn coffee is also gaining its popularity. Acorns are also used in flour making. 
</p>