<h2>Pine Tree Identification</h2>

Pine trees belong to the plant genus Pinus, as classified by taxonomists. There are two special features that distinguish pine trees from others. First, they grow a bract of cones that contain their seeds for propagation. And second, they sport narrow leaves. Their leaves can be so narrow it is referred to as needles and is usually arranged in bundles of two to five. 
<br /><br />
About 35 out of the 115 different species of pine trees are found in America alone. Pine trees are considered as evergreens and the cones serve as their flowers. Most pine trees are used for both ornamental and commercial purposes. 
<br /><br />
Pine trees are highly decorative. In fact, they are popular landscape trees. Some pine trees grow up to 60 feet high on the average with a horizontal spread of 30 feet. But could be short ones that grown only up to 20 feet tall and 15 feet wide.
<br /><br />
Most pine trees prefer full exposure to the sun and require little or no water at all during their full-grown stages. But some pine trees grow only in certain types of soils. Some Bristlecone pine, for example, prefers well-drained soils. The Black Pine, on the other hand, can grow on almost all types of soils. 
<br /><br />
Commercially, pines are used to manufacture wood pulp and timber. Some pine species have saps and resins that are good sources of turpentine. The species with large seeds, referred to as the pine nuts, are used in baking and cooking. And of course, no body can forget the most popular use for pine trees, especially during Christmas time. The whole tree, as well as its cones and leaves, are generally used as Christmas decorations. 
<br /><br />
Pine trees are also known for their pleasing smell. You will surely enjoy the good aroma of these trees as you pass through a lane lined with big and strong pine trees. But some people do find their scent somehow overbearing. And it can come too strong it could trigger an asthma attack on some. 
<br /><br />
Pine trees require maintenance too, that is if you intend to grow them naturally in your landscape. You have to watch out for pests and use fertilizers. But mostly, pine trees need attention as they grow. As they reach maturity, there would be no need to attend to them any longer. 


