<h2>The Evolution of Trees</h2>

Four hundred and seventy million years ago the earth was likely a very barren place without plants and animals, which is quite hard to imagine now because there are different types of plants and animals just about anywhere you look. The tree was one of the lucky living things that evolved from that time to become the beautiful thing that it is today.
<br /><br />
The evolution of trees into what they are today started a long time ago, in the ocean. Long before there was life outside of the water there were plants in the ocean that had already struggled to survive. Slowly, over time algae and other plants made their way onto the land, finding ways to bring water and support to their once water ridden structural systems. This was a difficult process, proven by the fact that it took so very long for plants and trees to find their way to dry land.
<br /><br />
Because of the arid land that the plants were trying to grow upon, they had to toughen up against the elements. So, over time the plants began to grow a bark for protection from the loss of water, harsh sunlight, so the evolution of wood is synonymous with that of the trees as it was an evolutionary side effect. Without bark trees could have never blossomed into the large, heavy plants that they are today because they would have been left without the proper protection from the elements.
<br /><br />
Trees started appearing quite late in our earths history, about three hundred and seventy million years ago. It is hard to imagine that the first animals had existed without the shade, protection, and foods that trees provide, but somehow they did. 

